on:
  push:
    branches: main

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::here
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up directories
        run: Rscript -e 'source("scripts/step1.R")'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: step1
          path: intermediates/step1.csv
  step2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::here
            any::dplyr
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up directories
        run: Rscript -e 'source("scripts/step2.R")'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: step2
          path: intermediates/step2.csv
  step3:
    runs-on: ubuntu-latest
    needs: [step1, step2]
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::here
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Downlodd artifacts
        uses: actions/download-artifact@v4
        with:
          path: intermediates
          merge-multiple: true
      - name: Stack files
        run: Rscript -e 'source("scripts/step3.R")'
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: done/*
          pull: '--no-rebase'
          author_name: GH Actions
          author_email: renatadiaz@arizona.edu